### ISSUE TITLE
C shared library support

### ISSUE THREAD

**Issue by RyanScottLewis** [nsf/termbox-go#117]
So we can easily create FFI and C extensions to Python, Ruby, etc. like here: https://blog.filippo.io/building-python-modules-with-go-1-5/

termbox-go is much better than it's C counterpart.

**Comment by imdaveho** [comment]
@RyanScottLewis please find my repo that does exactly this: https://github.com/imdaveho/intermezzo

I've also ported the demos into Python, but they are about 90-95% the same...variations are there due to the difference between Go and Python that I haven't sorted out. It's still in alpha, but I hope it helps!

Haven't uploaded to PyPi yet, but you can still `pip install .` after cloning.
