### ISSUE TITLE
syscall_OPOST or How to set our own syscall flags?

### ISSUE THREAD

**Issue by tombh** [nsf/termbox-go#128]
Do you know what [`syscall_OPOST` is used for](https://github.com/nsf/termbox-go/blob/master/api.go#L60)? Because it causes newlines to be written to remote PTY terminals when the termbox process isn't being given STDIN. I see it is to do with "output processing" http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap11.html#tag_11_01_08 But I don't completely understand it.

The bigger question is what is a good way to control which of these flags get set/unset?

**Comment by nsf** [comment]
I have no idea what it does either. The termios setup I'm using is taken from man pages mostly as an example of "raw terminal mode". And maybe I tweaked a few flags so that it appears to be working.

And what do you mean what is a good way to control it? There is no way, termbox just sets the flags. If you think we can remove some of them or change some of them - sure I don't mind. As long as termbox works as usual.

**Comment by tombh** [comment]
Ah right I see, thanks. Well I just need to comment out the `tios.Oflag &^= syscall_OPOST` and my program works again. So either I submit a PR removing that line or I submit a PR that allows for custom flag settings to override the defaults? But yeah, I don't understand it fully enough either :/

**Comment by nsf** [comment]
Ok, I'll try it and see if it works on different terminals, sorry a bit busy right now, maybe on a weekend.

**Comment by nsf** [comment]
Sorry, completely forgot about the issue, I think it's safe to remove OPOST as it's defined as "implementation-defined output processing". We don't need any implementation-defined output processing.
