### ISSUE TITLE
Pasting a string only fires an event for the first rune

### ISSUE THREAD

**Issue by moribellamy** [nsf/termbox-go#170]
Hi, apologies in advance if my ask is outside scope, or if I misunderstand anything.

It looks like `PollEvent() Event` is intended for clients to have a way to run their own business logic based on what's happening in the terminal. Of these "events" appears to be a KeyPress event, e.g. `event.Type = EventKey`

Based on some log-based debugging I did when playing with https://github.com/jroimartin/gocui, it appears that pasting a string only fires an event for the first thing in that string. So when I paste "When in the course of human events..." the user of this library only sees `%!(EXTRA termbox.Event={0 0 0 87 0 0 <nil> 0 0 1})`. Please let me know if this is intended behavior, or if you need more info to repro.

Not sure what the "best thing" to do here is. having an event for each character seems reasonable, if thats possible. Also having a "misc payload pasted" event seems reasonable.

**Comment by nsf** [comment]
If we're talking about terminal. There are no "events" per se, all you see from an OS is a stream of bytes. When user types "hello" or copy & pastes "hello", it all looks like a stream of bytes (5 bytes, "hello"). So, what you're asking is impossible to do. But on Windows it might be possible to handle copy & pasting better. I'm not sure why you're saying it's only first rune, you should get all runes in subsequent events. I know that because I'm using a text editor which is based on termbox and often paste text in it.

If you have some additional info of how it can be handled on the terminal level, let me know. But as far as I know, there is nothing you can do about it.

**Comment by moribellamy** [comment]
Sorry for the delay on this. Yep you're right -- I confirmed that I'm getting each of the keystrokes with a simple program that logs all events.

`go run log.go 2> foo.log`

https://gist.github.com/moribellamy/60b427b7544090304a392c57857527ec
