### ISSUE TITLE
How to enable cursor and avoid clean the screen?

### ISSUE THREAD

**Issue by manuel-rubio** [nsf/termbox-go#182]
I was using termbox for a project but I need to continue in the same screen and don't clean the screen. How can I achieve that? Thanks.

**Comment by nsf** [comment]
Not sure what you mean. But probably the fact that when termbox is initialized it clears the screen and then does so again when you go back to terminal. It's intentional. Termbox is not for drawing things in CLI mode. It's for full screen apps. If you need some progress bars or something for just half of the screen (ala docker). There are probably other libs to do so.

**Comment by mikijov** [comment]
I had a similar question. It is not a big deal for me. But my reason for not clearing the screen is that I want the user to feel like is continuing the work before and after calling my app. Yes, I would draw full screen eventually, but the experience of starting and exiting would be better in my case if my app continued where the last one stopped. 

While I would find this useful it is not a high priority for me.

**Comment by samliddicott** [comment]
What when termbox UI is used to reboot the box and/or kill an SSH session?
The terminal is then left in a bad condition, which box graphics characters showing, and a maybe hidden cursor.
It would be nice, if when reaching an idle state, termbox could take the terminal out of graphics mode, so that dropped connections are less likely to leave a useless terminal state.
It would be nice if this could be done deliberately, and show the cursor.

**Comment by alessio** [comment]
> I want the user to feel like is continuing the work before and after calling my app.

I'm exactly in the same position. Any updates?
