### ISSUE TITLE
copy-paste a string of chinese characters not working

### ISSUE THREAD

**Issue by nuberudi** [nsf/termbox-go#59]
I'm trying to use the "_demos/editbox.go" example as input window, when I try to enter chinese characters it only takes the first one of the keyboard input method selection, the same happens if I try to paste it from other source.
So for example:
I copy: 英國人
but it only paste 英人
Is this easy to solve?

**Comment by gdamore** [comment]
The problem is that the character you are pasting wide, so editbox is probably not quite right here.  That's just a demo program, so I wouldn't worry about it very much.

If you know you're going to be working with wide characters, you need to be careful in rendering them, understanding that each character may consist of multiple bytes, and may occupy either 1, 2, or even 0 cells.  Its hard to get this right without some care, and the Asian locales are the most confusing to deal with.

**Comment by gdamore** [comment]
Actually, even more confusing are bidi languages... :-)

**Comment by gdamore** [comment]
So it turns out not to have been as difficult as I feared -- provided we elide combining characters.  Double wide characters are fairly straight forward -- as seen above.  Please give it a try.

**Comment by thefallentree** [comment]
Hi there,

In order to make things more clear, I can provide an example:  

![image](https://cloud.githubusercontent.com/assets/1256464/11084280/6ffa677c-8874-11e5-8c55-b09b10897467.png)

![image](https://cloud.githubusercontent.com/assets/1256464/11084283/774faffa-8874-11e5-82d5-2f15ec1e29b0.png)

You can see there seems to be some width calculation error , the characters are not being fully displayed .

We are testing your fix right now, will let you know.

**Comment by gdamore** [comment]
Feel free also to give github.com/gdamore/tcell/termbox a shot.  I think it has a good chance of Just Working for you.  And it supports wide characters properly I think.  (And if you use the parent package instead, tcell, you get nice support for even combining characters.)

**Comment by thefallentree** [comment]
![image](https://cloud.githubusercontent.com/assets/1256464/11084677/36c215b8-8879-11e5-97bd-0698495d892f.png)

here are another demonstration.

**Comment by thefallentree** [comment]
@gdamore okay! we are giving it a shot! Thanks again for quick reply!

**Comment by kybin** [comment]
@thefallentree Termbox it self is not wrong. Error was in the example file. I just fixed it.

![new_tbprint](https://cloud.githubusercontent.com/assets/595519/11086333/5638fef6-8893-11e5-9d5a-fd0ea8958896.jpg)
