### ISSUE TITLE
Termbox 256 color ordering

### ISSUE THREAD

**Issue by JoelOtter** [nsf/termbox-go#93]
I'm trying to work out the rule for how the colors in 256-color mode are ordered. Is it _not_ the standard xterm colors as defined here?

http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html

Thanks.

**Comment by nsf** [comment]
You can just look at the code:

https://github.com/nsf/termbox-go/blob/master/termbox.go#L152-L199

and

https://github.com/nsf/termbox-go/blob/master/termbox.go#L85-L127

For 256 color mode it just writes the argument minus one, passing it to the terminal's SGR function. It should look exactly like that table you gave with the respect of a minus one thingy. The reason to have -1 there is because zero indicates "Default". And in xterm 256 color table, zero is black. I wanted to have a consistent "Default" and it being zero due to Go's default zero-initialization.

Documentation mentions that pretty clear: https://godoc.org/github.com/nsf/termbox-go#SetOutputMode

In the output demo there is a hidden control keys - left and right arrows, which change the output mode and demo it.

**Comment by JoelOtter** [comment]
I see! Great answer, thank you - didn't quite grasp the implications of having the default colour be zero.
