### ISSUE TITLE
[Question] Why using tty instead of stdin/stdout, or just a Reader and Writer?

### ISSUE THREAD

**Issue by zond** [nsf/termbox-go#96]
I am working on a small game, played via telnet connection.

I want to incorporate an editor in the game, and would like to just start the editor process with the net.Conn from the client as input/output.

I guess I could learn about how to create a new TTY, and somehow use that to start nsf/godit or build my own editor using termbox-go, but I am still uncertain about why termbox requires a TTY and not just readers/writers or stdin/stdout?

So, is there a short and sweet explanation about why a termbox library requires a TTY? :)

**Comment by nsf** [comment]
Termbox is a user interface abstraction, what it uses doesn't really matter, you shouldn't assume what it uses and how. I understand that when I say so, it means hiding implementation details explicitly and limiting what can be done with the lib. For example at some point there were guys who wanted to build ssh server with termbox-go integrated into it. But that's not the idea, the idea is the interface for gui applications. If you like the interface you can implement it by yourself. It's not hard at all. I've done it in a game engine as well, e.g.: http://i.imgur.com/UnOnF34.jpg. After all what termbox does is just converting an input stream to structured messages and then syncing its own back buffer with a very well defined format with a terminal.

I never really wanted to use termbox over the network quite frankly. I can imagine doing a simple transport layer which transfers a back buffer from a remote host to the local termbox app and delievring the input back.

But I don't know, not sure if all I said was helpful, but that's the answer I have.

P.S. I ended up rewriting GUI in my game engine from termbox to real GUI, because I think terminals suck: http://i.imgur.com/mCct348.png

**Comment by zond** [comment]
Ok - well, what I really want is a vim/emacs like editor that uses terminal codes on i/o streams to render a text based interface.

I just found http://github.com/buger/goterm which does this on stdin/stdout (IIUC), but I think what I should do is build a small library to simplify sending ANSI control codes, and then render this interface myself.

I agree that GUI is nicer than text, but it requires more work to get something done, and it's easier to describe a scene with words than pixels :)
